# Precificando mais casas

<img src="https://github.com/alura-cursos/data-science-regressao-linear/blob/main/imagens/precificando_mais_casas.webp?raw=true" alt="Imagem de uma casa e suas características para precificação" width=720>

Agora chegou a hora de testarmos o nosso modelo para mais casas!

### **Lendo o DataFrame com as casas a precificar**

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Lendo a base das casas a precificar
casas = pd.read_csv('dados/casas_a_precificar.csv')
casas.head()

   area_primeiro_andar  existe_segundo_andar  area_quintal  dist_metro
0                  180                     1            40         8.0
1                  130                     0            80         1.0
2                  170                     1            60         7.5
3                  250                     1            70         4.0
4                  260                     0            70         8.5

In [5]:
# Ajustando a coluna dos dados
casas.columns = ["log_area_primeiro_andar", "existe_segundo_andar", "log_area_quintal", "log_dist_metro"]

In [6]:
# Calculando o logaritmo das variaveis
casas['log_area_primeiro_andar'] = np.log(casas['log_area_primeiro_andar'])
casas['log_area_quintal'] = np.log1p(casas['log_area_quintal'])
casas['log_dist_metro'] = np.log(casas['log_dist_metro'])

In [7]:
casas

,log_area_primeiro_andar,existe_segundo_andar,log_area_quintal,log_dist_metro
0,5.192957,1,3.713572,2.079442
1,4.867534,0,4.394449,0.000000
2,5.135798,1,4.110874,2.014903
3,5.521461,1,4.262680,1.386294
4,5.560682,0,4.262680,2.140066
5,5.298317,0,4.948760,0.405465
6,5.703782,0,4.948760,1.609438
7,4.787492,0,4.110874,2.302585
8,4.787492,1,4.615121,0.405465
9,4.787492,1,3.713572,2.014903

### **Importando o modelo salvo em pickle**

In [8]:
import pickle

In [9]:
# Importando o modelo
m = open('modelo_precifica_casas', 'rb')
modelo = pickle.load(m)
m.close()

### **Estimando o preço das casas**

In [10]:
# Prevendo os valores das casas
previsoes = modelo.predict(casas)
previsoes

array([13.7089794 , 13.95497022, 13.72879066, 14.09743924, 13.73265545,
       14.10842228, 13.99698273, 13.29196957, 14.0145501 , 13.52325782])

In [11]:
# Exibindo os valores em reais
for i, previsao in enumerate(previsoes):
  print(f'Casa {i+1} --> R$ {np.exp(previsao):,.2f}')

Casa 1 --> R$ 898,947.04
Casa 2 --> R$ 1,149,652.43
Casa 3 --> R$ 916,933.89
Casa 4 --> R$ 1,325,684.17
Casa 5 --> R$ 920,484.50
Casa 6 --> R$ 1,340,324.47
Casa 7 --> R$ 1,198,981.17
Casa 8 --> R$ 592,419.08
Casa 9 --> R$ 1,220,230.22
Casa 10 --> R$ 746,579.82